# Generated by Django 5.0 on 2023-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_tv_text', models.TextField(verbose_name='English TV отношение')),
                ('ru_tv_text', models.TextField(verbose_name='Russian TV отношение')),
                ('tv_statistic', models.SmallIntegerField()),
                ('newspaper_statistic', models.SmallIntegerField()),
                ('radio_statistic', models.SmallIntegerField()),
                ('internet_statistic', models.SmallIntegerField()),
                ('friend_statistic', models.SmallIntegerField()),
            ],
        ),
    ]
