# Generated by Django 5.0 on 2023-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'информацию', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AddField(
            model_name='data',
            name='en_statistic_text',
            field=models.TextField(blank=True, null=True, verbose_name='О статистике EN'),
        ),
        migrations.AddField(
            model_name='data',
            name='ru_statistic_text',
            field=models.TextField(blank=True, null=True, verbose_name='О статистике RU'),
        ),
        migrations.AlterField(
            model_name='data',
            name='en_tv_text',
            field=models.TextField(blank=True, null=True, verbose_name='Отношение к телику EN'),
        ),
        migrations.AlterField(
            model_name='data',
            name='friend_statistic',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент СЛУХОВ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='internet_statistic',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент ИНТЕРНЕТА'),
        ),
        migrations.AlterField(
            model_name='data',
            name='newspaper_statistic',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент ГАЗЕТ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='radio_statistic',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент РАДИО'),
        ),
        migrations.AlterField(
            model_name='data',
            name='ru_tv_text',
            field=models.TextField(blank=True, null=True, verbose_name='Отношение к телику RU'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tv_statistic',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент ТВ'),
        ),
    ]
