# Generated by Django 5.0 on 2023-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_data_options_data_en_statistic_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='friend_statistic',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент СЛУХОВ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='internet_statistic',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент ИНТЕРНЕТА'),
        ),
        migrations.AlterField(
            model_name='data',
            name='newspaper_statistic',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент ГАЗЕТ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='radio_statistic',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент РАДИО'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tv_statistic',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент ТВ'),
        ),
    ]
